### ISSUE TITLE
Initialize throws error on iOS 9

### ISSUE THREAD

**Issue by c-goettert** [lucaspbordignon/rn-apple-healthkit#104]
First of all, thanks for this really helpful library. I am facing an issue on devices running iOS 9.3.3. After checking the XCode-logs I found that the follwoing lines are causing an exeption:

RCTAppleHealthKit+TypesAndPermissions.m:
```
52: @"MindfulSession" : [HKObjectType categoryTypeForIdentifier:HKCategoryTypeIdentifierMindfulSession]
...
119: @"MindfulSession" : [HKObjectType categoryTypeForIdentifier:HKCategoryTypeIdentifierMindfulSession],
```

After commenting out those lines, the initialization works fine again for me. Could it be that MindfulSessions are not supported in iOS 9?

**Comment by terrillo** [comment]
Hey @c-goettert checkout the new 0.7.2v release. This should no longer be an issue

Thanks,

**Comment by c-goettert** [comment]
Seems to work now, thanks.
