### ISSUE TITLE
Auto linking not supported , How we configure this in latest version of react native which is only supported autoLinking.

### ISSUE THREAD

**Issue by Farhankhalid33100** [lucaspbordignon/rn-apple-healthkit#112]

**Comment by younss** [comment]
see this https://github.com/terrillo/rn-apple-healthkit/pull/111

**Comment by c-goettert** [comment]
I guess this means we just add it to our pod-file like:
```pod 'RCTAppleHealthKit', path: '../node_modules/rn-apple-healthkit'```
instead of steps 2.-5. of the manual linking steps in the readme?

I think an update of the docs would be helpful :)

**Comment by terrillo** [comment]
@c-goettert issue fixed in https://github.com/terrillo/rn-apple-healthkit/releases/tag/0.7.0v
