### ISSUE TITLE
Support of this library

### ISSUE THREAD

**Issue by younss** [lucaspbordignon/rn-apple-healthkit#113]
Hi @terrillo ,

This library has many pull requests in pending status but there is no review.
Can you please give the project to the community and add contributors.
Very interesting things are done by other contributors but code is not merged.

Kind regards.

**Comment by terrillo** [comment]
Hey @younss, made couple of releases. https://github.com/terrillo/rn-apple-healthkit/releases
Also working on a new 1.0v branch to fix some core issues. https://github.com/terrillo/rn-apple-healthkit/issues/120

If you interested in becoming a contributor. Send me an email.

Thanks
