### ISSUE TITLE
0.7 release: Could not find the following native modules: RCTAppleHealthKit. 

### ISSUE THREAD

**Issue by djarrin** [lucaspbordignon/rn-apple-healthkit#119]
After running the commands

```npm install rn-apple-healthkit --save ```
```react-native link rn-apple-healthkit```
```react-native run-ios```

 - rn-apple-healthkit (to unlink run: "react-native unlink rn-apple-healthkit")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

I get the error: Could not find the following native modules: RCTAppleHealthKit. Did you forget to run "pod install" ?

When I keep rn-apple-healthkit linked I get this when trying to run pod install in the ios folder:
[!] The `RCTAppleHealthKit` pod failed to validate due to 1 error:
    - WARN  | description: The description is equal to the summary.
    - ERROR | [iOS] name: The name of a spec should not contain whitespace.

When I unlink rn-apple-healthkit I get this:
when I go into the ios folder and run pod install I get: [!] No podspec found for `React Apple Healthkit` in `../node_modules/rn-apple-healthkit`

**Comment by terrillo** [comment]
Hey @djarrin just pushed 0.7.1v that should fix this issue. Still looking into a proper way to handle migration from below 0.60 to 0.60 or above
