### ISSUE TITLE
Duplicate declaration of method activity_getBasalEnergyBurned

### ISSUE THREAD

**Issue by crrobinson14** [lucaspbordignon/rn-apple-healthkit#121]
This recently merged/released PR is creating a duplicate-declaration error for me in XCode:

https://github.com/terrillo/rn-apple-healthkit/pull/49/files#diff-b6a35937d5c09cce78cff29d1f49dd41R17

![image](https://user-images.githubusercontent.com/1675563/68715152-926e7a80-055e-11ea-8c8c-0593f13a213b.png)

**Comment by terrillo** [comment]
See https://github.com/terrillo/rn-apple-healthkit/commit/fdfe6c12f97f8e6d7e7121b79219d59b6439daf7 and try 0.7.3v. Sorry about that. Tested on a clean build this time :D

**Comment by crrobinson14** [comment]
@terrillo Works great, thanks!
