### ISSUE TITLE
React/RCTBridgeDelegate.h file not found

### ISSUE THREAD

**Issue by adam-hanna** [lucaspbordignon/rn-apple-healthkit#13]
**EDIT** - I'm really confused. The file is in the directory `/Users/adamhanna/Desktop/goLang/src/personal/rise/rise/node_modules/react-native/React/Base`, when I add that exact directory to my headers search path, it still errors. WTH?!

I installed the project automatically with yarn and react-native link rn-apple-healthkit but I'm still getting this error. See the error and my header search paths in the image, below. I'm at my wits end, any help would be appreciated. Thx

![screen shot 2017-12-08 at 12 00 33 am](https://user-images.githubusercontent.com/5436950/33756594-215e100a-dbab-11e7-918b-086b2df04dc9.png)

**Comment by adam-hanna** [comment]
Ok, so I changed `#import React/RCTBridgeModule.h` to `#import "RCTBridgeModule.h"` and a whole bunch of similar and it's working.

I'm using Expo's react native https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz, which must be using a <0.40? Maybe I'll see if Expo has a more recent version...

**Comment by AmitPandya007** [comment]
> Ok, so I changed `#import React/RCTBridgeModule.h` to `#import "RCTBridgeModule.h"` and a whole bunch of similar and it's working.
> 
> I'm using Expo's react native https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz, which must be using a <0.40? Maybe I'll see if Expo has a more recent version...

@adam-hanna 
Did it work? Coz I am still getting 'RCTBridgeModule.h' file not found Error. Can you help me out to set up and Run this. 
Thanks, in Advance.
