### ISSUE TITLE
can't find variable: AppleHealthkit

### ISSUE THREAD

**Issue by ghost** [lucaspbordignon/rn-apple-healthkit#16]
Why did I get this error?

**Comment by ChaoTzuJung** [comment]
`AppleHealthkit.initStepCountObserver({}, () => {}); `
should be 
`AppleHealthKit.initStepCountObserver({}, () => {});` 
with capital K

**Comment by Aishwarya-Surana** [comment]
@yamato-hara how were you able to sort it out?

**Comment by terrillo** [comment]
Updated docs to reflect https://github.com/terrillo/rn-apple-healthkit/wiki/initStepCountObserver() 👍
