### ISSUE TITLE
check granted 'read' permissions

### ISSUE THREAD

**Issue by agnieszkabugla** [lucaspbordignon/rn-apple-healthkit#169]
Is there a way to check if my application is granted 'read' permissions by the user? 

I know of `AppleHealthKit.authorizationStatusForType("StepCount")` that checks 'write' permissions. But is there a way to check which 'read' permissions user granted?

**Comment by Frans-L** [comment]
By reading Apple's documentation, it seems not to be possible :/

"Users can grant or deny permission separately for each type of data. For example, a user could let your app read the step count data but prevent it from reading the blood glucose level. To prevent possible information leaks, **an app does not know whether it has been denied permission to read data**. From the app’s point of view, if the app has been denied permission to read data, no data of that type exists."

https://developer.apple.com/documentation/healthkit/protecting_user_privacy

**Comment by agnieszkabugla** [comment]
I was afraid of that. Thank you @Frans-L  for your quick response.
