### ISSUE TITLE
Build fails on 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by adcuz** [lucaspbordignon/rn-apple-healthkit#17]
Is this library compatible with the latest versions of React Native? I can't get it to work, as there seems to be some issues with Header imports not being found. I've searched for hours with potential fixes such as changing the Header Search paths, but no luck.

`'React/RCTBridgeModule.h' file not found`

![Shot](https://i.imgur.com/hJaZc9w.png)

**React Native Version**
0.51.0

I've tried running Clean in Xcode after removing the rn-apple-healthkit and unlinking, then reinstalling again, still the issue persists.

Has anyone else been able to get it to build on newer versions of React Native?

**Comment by adcuz** [comment]
I found the fix for this, it turns out the issue may be due to the fact my app is a detached ExpoKit app.

Recent changes to React Native mean libraries without CocoaPods support may have trouble including header files. You can see a more detailed description in the [Expo Docs](https://docs.expo.io/versions/latest/guides/expokit.html#if-the-library-doesnt-support-cocoapods-react-native-link-may-fail-to-include-the-librarys-header-files-if-you-encounter-build-issues-locating-the-react-headers-you-may-need-to-manually-add-podsheaderspublic-to-the-header-search-paths-configuration-for-your-native-dependency-in-xcode-if-youre-not-familiar-with-xcode-search-xcode-help-for-configure-build-settings-to-get-an-idea-of-how-those-work-header-search-paths-is-one-such-build-setting-the-target-you-care-to-configure-is-the-one-created-by-react-native-link-inside-your-xcode-project-youll-want-to-determine-the-relative-path-from-your-library-to-podsheaderspublic). Here is a [thread I found with more details](https://forums.expo.io/t/how-do-i-manually-add-pods-headers-public-to-the-header-search-paths-configuration/2427/14) about setting the header search path to point at Pods/Headers/Public directory.

In my case, I added a Header Search path `${SRCROOT}/../../ios/Pods/Headers/Public` (Recursive) and the build succeeded.

![](https://i.imgur.com/AdSd8O8.png)

Ultimately it'd be really good if this library could add CocoaPods support, I'd do it myself but I would struggle as I am not familiar with iOS dev beyond the JS side of React Native.

**Comment by adcuz** [comment]
Strange, I upgraded ExpoKit to 25.0.0 and now the above fix doesn't work. So the above fix perhaps was not the correct answer. Anyone who can help would be hugely appreciated.

**Comment by maxweb4u** [comment]
Anyone can help with this issue ?

**Comment by rovaniemi** [comment]
@adcuz did you get this problem solved?

**Comment by maxweb4u** [comment]
@rovaniemi I fixed like - I removed this module from my project and added my own native module to ios project using some functions from this module.

**Comment by jtsiskin** [comment]
I was able to fix this by not only adding ${SRCROOT}/../../ios/Pods/Headers/Public (Recursive) as shown https://github.com/terrillo/rn-apple-healthkit/issues/17#issuecomment-360537876 to both the project and the target.  Just adding it to the project did not work.
![image](https://user-images.githubusercontent.com/11904459/47970529-c31afa80-e054-11e8-985b-d34be5bf0460.png)
![image](https://user-images.githubusercontent.com/11904459/47970531-c9a97200-e054-11e8-940f-d6491b565b53.png)

**Comment by cryptixcoder** [comment]
This didn't solve the issue for me.

**Comment by stam** [comment]
Changing some xcodeproj settings in a project in your node_modules seem like an extremely nasty workaround. What if you have a CI/CD pipeline in place?

**Comment by dkarp0** [comment]
We have a CI/CD pipeline in place that this was causing issues with. An unfortunately hacky solution is to run a `postinstall` step in the `packages.json` file that runs a script that adds the `HEADER_SEARCH_PATHS` if they aren't set.

Place the following in a `fix-rn-apple-healthkit.rb` file:
```
require 'xcodeproj'
project_path = 'node_modules/rn-apple-healthkit/RCTAppleHealthKit.xcodeproj/'
project = Xcodeproj::Project.open(project_path)

path = "${SRCROOT}/../../ios/Pods/Headers/Public/**"

def add_to_build_settings(path, build_settings)
    (build_settings['HEADER_SEARCH_PATHS'] ||= []) << path
end

def check_for_existing(path, build_settings)
    if build_settings.include? "HEADER_SEARCH_PATHS"
        return build_settings['HEADER_SEARCH_PATHS'].include?(path) 
    else
        return FALSE
    end
end

project.build_configurations.each do |config|
    add_to_build_settings(path, config.build_settings) unless check_for_existing(path, config.build_settings) 
end
project.targets.each do |target|
    target.build_configurations.each do |config|
        add_to_build_settings(path, config.build_settings) unless check_for_existing(path, config.build_settings)  
    end
end

project.save()
```

Then something like the following in `packages.json`:
```
"scripts": {
    "postinstall": "type ruby && ruby fix-rn-apple-healthkit.rb"
  },
```
