### ISSUE TITLE
getting error on getStepCount()

### ISSUE THREAD

**Issue by ZishanK** [lucaspbordignon/rn-apple-healthkit#177]
hi, i'm getting below error when i call getStepCount():
{"code": "E(null)0", "domain": "RCTErrorDomain", "message": "Unknown error from a native module", "nativeStackIOS": ["0                                 0x00000001094736a7 RCTJSErrorFromCodeMessageAndNSError + 135", "1                                 0x00000001094735d3 RCTJSErrorFromNSError + 275", "2                                0x00000001092b43ff __73-[RCTAppleHealthKit(Methods_Fitness) fitness_getStepCountOnDay:callback:]_block_invoke + 207", "3                                 0x00000001092c984a __80-[RCTAppleHealthKit(Queries) fetchSumOfSamplesOnDayForType:unit:day:completion:]_block_invoke + 314", "4   libdispatch.dylib                   0x000000010c67df11 _dispatch_call_block_and_release + 12", "5   libdispatch.dylib                   0x000000010c67ee8e _dispatch_client_callout + 8", "6   libdispatch.dylib                   0x000000010c6856fd _dispatch_lane_serial_drain + 788", "7   libdispatch.dylib                   0x000000010c6862c5 _dispatch_lane_invoke + 476", "8   libdispatch.dylib                   0x000000010c691b65 _dispatch_workloop_worker_thread + 719", "9   libsystem_pthread.dylib             0x00007fff522b3a3d _pthread_wqthread + 290", "10  libsystem_pthread.dylib             0x00007fff522b2b77 start_wqthread + 15"], "userInfo": null}

my method is this:
AppleHealthKit.getStepCount(null, (err, results) => {
            
            if (err) {
              console.log("getStepCount error",err)
                return;
            }
            console.log("getStepCount",results)
        });

Please let me know if anybody can help, thank you.

**Comment by rodriigovieira** [comment]
Refer to this issue: https://github.com/terrillo/rn-apple-healthkit/issues/128

You have to add the data manually at the iOS Simulator.

**Comment by ZishanK** [comment]
@rodriigovieira , thanks for your kind reply. But i'm testing it on real device and not understanding where the issue is.

**Comment by rodriigovieira** [comment]
@ZishanK I believe that if there's no data registered in the HealthKit, an error will be thrown. So, to test it, you would have to add data manually.

I added steps manually for a few days in the simulator and after that it worked. What I'm doing in these cases is simply return a 0 when an error is thrown.

**Comment by ZishanK** [comment]
i've data in healthkit for stepcount, but can i get to know that how can i add it manually?

**Comment by rodriigovieira** [comment]
You simply open the Health app, then go Steps, and at the top-right corner there'll be a button to add data manually.

**Comment by ZishanK** [comment]
@rodriigovieira thanks resolved by adding steps manually.
