### ISSUE TITLE
App Store Distribution fails on valid com.apple.developer.healthkit.access value

### ISSUE THREAD

**Issue by sorjames** [lucaspbordignon/rn-apple-healthkit#201]
Deploy to testflight failed

ios/app/app.entitlements
<key>com.apple.developer.healthkit.access</key>
<array/>

ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ ]' for the key 'com.apple.developer.healthkit.access' in 'Payload/app.app/app'."

https://developer.apple.com/forums/thread/671352

**Comment by caglardurmus** [comment]
same issue

**Comment by caglardurmus** [comment]
I found this solution but i don't will it work in review. 

https://stackoverflow.com/questions/65712249/the-entitlements-in-your-app-bundle-signature-do-not-match-the-ones-that-are-con

**Comment by IceDev-xyz** [comment]
I can confirm, the current solution works in App Review. 

Remove, comment these lines from your production entitlements. `/PROJECT/ios/PROJECT/PROJECT.entitlements`

`<key>com.apple.developer.healthkit.access</key>
<array/>`

This is an Xcode - Apple issue, not related to this library.

Closing this issue

**Comment by sorjames** [comment]
update apple fixed this issue thankyou
