### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by bdspen** [lucaspbordignon/rn-apple-healthkit#36]
I followed the manual install directions exactly and when I build the project I am receiving this error.

the line is: #import <React/RCTBridgeModule.h>
line 12 of RCTAppleHealthKit.h

    "react": "15.3.2",
    "react-native": "0.34.1",
    "rn-apple-healthkit": "^0.6.3",

**Comment by redpandatronicsuk** [comment]
Have a look at: https://github.com/terrillo/rn-apple-healthkit/issues/17#issuecomment-360537876
