### ISSUE TITLE
HealthKit cannot initialize

### ISSUE THREAD

**Issue by bdspen** [lucaspbordignon/rn-apple-healthkit#37]
after [installing](https://github.com/terrillo/rn-apple-healthkit#installation) the library and calling `AppleHealthKit.initHealthKit`
I get the following error:
<img width="374" alt="screen shot 2018-05-23 at 6 33 43 pm" src="https://user-images.githubusercontent.com/12138132/40459727-e2e4f894-5eb7-11e8-9446-b9843be26895.png">

When I inspect the `AppleHealthKit` imported object, there is just "constants" and "permissions" properties, no methods.

**Comment by gitpayal** [comment]
@bdspen  are you able to resolve this issue? I am facing same issue

**Comment by JulianKingman** [comment]
Looks like a linking issue. Did you run `react-native link rn-apple-healthkit`, or use cocoapods?

**Comment by lytieunuong1** [comment]
I think you forgot this step:
`4. In XCode, in the project navigator, select your project. Add libRCTAppleHealthkit.a to your project's Build Phases ➜ Link Binary With Libraries`

**Comment by EJohnF** [comment]
seems to be resolved, since no more responses
