### ISSUE TITLE
Is there a way to get any subscriber for heart rate as well , similar to step count ??

### ISSUE THREAD

**Issue by shrinandhini2801** [lucaspbordignon/rn-apple-healthkit#43]
Is there a way to get any subscriber for heart rate as well , similar to step count ?? Like i need to get intimated whenever there is a change in the heart rate value in health kit .

**Comment by JulianKingman** [comment]
Not yet, I have this rfc open for this feature: https://github.com/terrillo/rn-apple-healthkit/issues/65

Comments welcome.
