### ISSUE TITLE
Can't write Blood Pressure (Systolic or Diastolic)

### ISSUE THREAD

**Issue by stippets** [lucaspbordignon/rn-apple-healthkit#48]
In the documentation it states that you can write both systolic and diastolic blood pressure data. I read through the source code and can't find anything that seems to support this. Am I missing something?

**Comment by SirBryan** [comment]
When I was looking through this the other day (for what you are referencing), it appears the docs are talking about HealthKit's ability to read/write items.  The JS methods for most of HK's capabilities are incomplete.
