### ISSUE TITLE
Typo in initHealthKit() wiki

### ISSUE THREAD

**Issue by glocore** [lucaspbordignon/rn-apple-healthkit#52]
Please replace `AppleHealthkit.initHealthKit` with `AppleHealthKit.initHealthKit` (uppercase K in AppleHealthKit) in the last code snippet in the [initHealthKit()](https://github.com/terrillo/rn-apple-healthkit/wiki/initHealthKit()) wiki.
EDIT: This typo is repeated in many other Wiki pages as well.

**Comment by terrillo** [comment]
💯 👍
