### ISSUE TITLE
getStepCount()

### ISSUE THREAD

**Issue by geniuscd** [lucaspbordignon/rn-apple-healthkit#55]
Hey,
I'm calling the "getStepCount()" method without any option, its getting the current date (default value), but if I set in the options(dictionary) a date key and a value its returning an error *'could not fetch step count for day'* . anyone having the same issue?
following this link: https://github.com/terrillo/rn-apple-healthkit/wiki/getStepCount()

**Comment by AnyIdeasAds** [comment]
Hey, @geniuscd how did you solve this?

**Comment by JulianKingman** [comment]
Did you use `date.toISOString()`?
