### ISSUE TITLE
Is there any plans to support this repository? 

### ISSUE THREAD

**Issue by EJohnF** [lucaspbordignon/rn-apple-healthkit#62]
@terrillo I see that your last activity here was pretty long time ago. Do you have any plans for this library? I'd love to spend some effort to make this project live again

**Comment by JulianKingman** [comment]
@terrillo there are quite a few open PR's and many people who would want to contribute to make this a fully featured library. EJohnF has been pretty active with the repo, adding him as a collaborator would be a great start.

**Comment by nabylb** [comment]
It would be great to add somebody active as a contributor. I had to fork this repo to update it for my project.

**Comment by terrillo** [comment]
https://github.com/terrillo/rn-apple-healthkit/issues/64
