### ISSUE TITLE
Updating repo & looking for collaborators

### ISSUE THREAD

**Issue by terrillo** [lucaspbordignon/rn-apple-healthkit#64]
Hey Everyone,

Looking to add collaborators.  I'm going to start reviewing open pull requests and get the ball rolling again. 👍 

Comment below if your interested in becoming a collaborator.

**Comment by JulianKingman** [comment]
You're the man! I'm interested in getting more HKObserverQueries set up, so set me up as a collaborator.

**Comment by EJohnF** [comment]
Hi!
I'm interested to support this project.

**Comment by terrillo** [comment]
@EJohnF @JulianKingman sent invites 👍

**Comment by nabylb** [comment]
Same here. I would love to support this as we need it in our project.

**Comment by AFGhazy** [comment]
me 2

**Comment by golles** [comment]
Hi, would be great to see you guys could review some PR's and get them merged. Thanks a lot!

**Comment by nabylb** [comment]
I would love to but I was never added as a contributor.
