### ISSUE TITLE
Workouts

### ISSUE THREAD

**Issue by anna-sunberg** [lucaspbordignon/rn-apple-healthkit#7]
Any way to get workout data?

**Comment by matthiasn** [comment]
This would be really helpful. Thanks for the library 👍

**Comment by edencakir** [comment]
Any update on this?

**Comment by wvteijlingen** [comment]
I'm currently working on adding support for writing workouts. Adding read support wouldn't be to hard. I'll keep you guys posted!

**Comment by markwk** [comment]
@wvteijlingen Do you know if "exercise minutes" are part of the workouts' data or somewhere else? I'd be interested in accessing and leveraging that data.

**Comment by matthiasn** [comment]
Any updates on this? Thanks

**Comment by wvteijlingen** [comment]
I’m using a fork now that supports writing workout data. Haven’t gotten around to implementing reading yet because the query options are pretty extensive. It would be quite a bit of work to support them all.

If you want I’ll create a pull request for the writing functionality.

**Comment by matthiasn** [comment]
@wvteijlingen please, that would be a good start. Thanks

**Comment by wvteijlingen** [comment]
Pull request: https://github.com/terrillo/rn-apple-healthkit/pull/14

**Comment by EJohnF** [comment]
https://github.com/EJohnF/rn-apple-healthkit/tree/newFeatures

and some other tasty features (like isTracked and source information)

**Comment by iMaciah** [comment]
Any update on reading workouts?

**Comment by EJohnF** [comment]
https://github.com/terrillo/rn-apple-healthkit/pull/25

**Comment by EJohnF** [comment]
https://github.com/terrillo/rn-apple-healthkit/blob/master/docs/getSamples().md
