### ISSUE TITLE
Does this also do background observer. 

### ISSUE THREAD

**Issue by manujbahl** [lucaspbordignon/rn-apple-healthkit#70]
Does this plugin also retrieve background data?
Does initStepCountObserver call on the background fetch as well

**Comment by EJohnF** [comment]
I think it should. 

or you can use setObserverForType here https://github.com/terrillo/rn-apple-healthkit/pull/25

**Comment by EJohnF** [comment]
https://github.com/terrillo/rn-apple-healthkit/blob/master/docs/setObserver().md
