### ISSUE TITLE
_this2._handleHealthKitError is not a function

### ISSUE THREAD

**Issue by LudinaReema** [lucaspbordignon/rn-apple-healthkit#75]
When I tried to run the code, I am getting "_this2._handleHealthKitError is not a function" error. If I comment "this._handleHealthKitError () ", getting the result as { value: null, age: null }.

**Comment by JulianKingman** [comment]
Sounds like it may not be linked properly. Under "Build Phases/Link Binary With Libraries" in xcode, can you make sure that "libRCTAppleHealthKit.a" is linked? If it's not there, press the "+" button and add it.

**Comment by LudinaReema** [comment]
@JulianKingman It is linked. Still, I am getting that issue.

**Comment by JulianKingman** [comment]
Can you post the code you're using?

**Comment by LudinaReema** [comment]
AppleHealthKit.initHealthKit(options: Object, (err: string, results: Object) => {
    if (err) {
        console.log("error initializing Healthkit: ", err);
        return;
    }
 
    // Height Example
    AppleHealthKit.getDateOfBirth(null, (err: Object, results: Object) => {
    if (this._handleHealthkitError(err, 'getDateOfBirth')) {
      return;
    }
      console.log(results)
    });
});

I tried to work without this._handleHealthkitError().

   AppleHealthKit.getDateOfBirth(null, (err: Object, results: Object) => {
    if (err) {
      return;
    }
      console.log(results)
    });
Now it works fine for me.

**Comment by EJohnF** [comment]
Seems issue is resolved
