### ISSUE TITLE
Listener 'observer' take a while to fire ?

### ISSUE THREAD

**Issue by gus-waritthorn** [lucaspbordignon/rn-apple-healthkit#80]
I'm building application that want to show user step in realtime but listener take too long to invoke.
Is it possible to show healthkit user step in realtime ?

this is my code
```
async componentDidmount() {
    AppleHealthKit.initHealthKit(HKOPTIONS, (err, res) => {
        if (err) {
            console.log('error initializing Healthkit: ', err);
            return;
        }
        AppleHealthKit.setObserver({ type: 'Walking' });
        NativeAppEventEmitter.addListener('observer', () => console.log('fetch new data'));
    });
}
```

**Comment by EJohnF** [comment]
AppleHealthKit.setObserver - this is mostly for background and we can't control when healthKit would fire this event. 
It might happens in 5 mins or 20

**Comment by gus-waritthorn** [comment]
So initStepCountObserver() use to detect value change when application in foreground
and setObserver use to detect value change when application in background ?

if i understand it correctly. Is this code below use setObserver with react-native-background-timer in a right way or not ?
```
BackgroundTimer.runBackgroundTimer(() => { 
    //code that will be called every 3 seconds
    AppleHealthKit.setObserver({ type: 'Walking' });
    NativeAppEventEmitter.addListener('observer', () => console.log('fetch new data'));
}, 3000);
```

**Comment by EJohnF** [comment]
> initStepCountObserver

I've checked that, no - it also use background way.
Under both this calls https://developer.apple.com/documentation/healthkit/hkobserverquery is used. 

So, if you need to do it in foreground, I can suggest you only to check every second(or so) for new data available or not. 
But normally, from my experience, HealthKit publish information with some delay (even in native Health app you can't see step changes with each your step during walking)
