### ISSUE TITLE
How to check permission grants?

### ISSUE THREAD

**Issue by adamnator92** [lucaspbordignon/rn-apple-healthkit#82]
As mention above, how do i check permissions granted for certain action?

**Comment by ghost** [comment]
Use `AppleHealthKit.authorizationStatusForType`, [see here](https://github.com/terrillo/rn-apple-healthkit/blob/master/docs/authorizationStatusForType().md).

**Comment by jeremybenaim** [comment]
@xkvcr this method doesn’t seem available.. :/ 

You can see that by inspecting the lib in your code `console.dir(AppleHealthKit)`

**Comment by crrobinson14** [comment]
It seems this was added and documented but never actually released?

**Comment by jeremybenaim** [comment]
@crrobinson14 yep, precisely
