### ISSUE TITLE
No source in getBloodGlucoseSamples result objects

### ISSUE THREAD

**Issue by yonatanlozinsky** [lucaspbordignon/rn-apple-healthkit#89]
Hi and thanks for this package, it really helped me!

Right now what I get from getBloodGlucoseSamples() is startDate, endDate and value.

I also need the source of the record, and I can see it in the HealthKit app for each record.
Is this possible to add this property to the object?
If not, can I get it in any other way?

Thanks in advance :)

**Comment by iradkot** [comment]
Hey @luzushka, I've just added a PR that fixes this issue.
Could you please merge it? @terrillo @EJohnF

**Comment by Moshikol** [comment]
+1

**Comment by EJohnF** [comment]
merged
