### ISSUE TITLE
Not able to call any function

### ISSUE THREAD

**Issue by iampatman** [lucaspbordignon/rn-apple-healthkit#9]
Hi Terillo,

I am new to React Native, I have npm installed and link the package.

I put this code in render
`let options = {
      permissions: {
        read: ['Height', 'Weight', 'StepCount', 'DateOfBirth', 'BodyMassIndex'],
        write: ['Weight', 'StepCount', 'BodyMassIndex']
      }
    }
    AppleHealthKit.isAvailable((err: Object, available: boolean) => {
      if (err) {
        console.log('error initializing Healthkit: ', err)
        return
      }
      // Healthkit is available
    })`

But this showed up

<img width="375" alt="screen shot 2017-11-15 at 17 28 14" src="https://user-images.githubusercontent.com/16368580/32828899-65337ec8-ca2b-11e7-8c13-00552eb21674.png">

Please let me know if there is anything I should pay attention to.

**Comment by iampatman** [comment]
It worked when I created a blank new project and do things from the ground up.

**Comment by seanking11** [comment]
I was having the same problem and needed to restart the project via `react-native run-ios` again. 

It looks like whenever you run `react-native link example-repo`, you should restart the project to eliminate errors.

**Comment by bad6e** [comment]
I am having the same problem. Restarted and reloaded everything. Tried manual and auto install. The `AppleHealthKit` isn't part of the native modules.
