### ISSUE TITLE
sample code fails with SyntaxError

### ISSUE THREAD

**Issue by z00m1n** [lucaspbordignon/rn-apple-healthkit#92]
I followed the [installation instructions](https://github.com/terrillo/rn-apple-healthkit#installation) to the letter and copied & pasted the [sample code](https://github.com/terrillo/rn-apple-healthkit#get-started) to the `App.js` file of my application. When trying to run it, I get an error message

```
SyntaxError: /Users/ssc/DevBase/Crumb/Projects/crumb/Mobile/code/crumb/App.js: The type cast expression is expected to be wrapped with parenthesis (34:36)

  32 | import AppleHealthKit from 'rn-apple-healthkit';
  33 | 
> 34 | AppleHealthKit.initHealthKit(options: Object, (err: string, results: Object) => {
     |                                     ^
  35 |     if (err) {
  36 |         console.log("error initializing Healthkit: ", err);
  37 |         return;
```

How can I fix this ?

**Comment by psousa** [comment]
Hi! Use:
`AppleHealthKit.initHealthKit(options, (err, results) => {`

**Comment by alexdevero** [comment]
@z00m1n Example code is written in TypeScript. Either follow advice of @psousa or add TypeScript to your app.

**Comment by z00m1n** [comment]
Thank you very much! :-)
